<a href="https://colab.research.google.com/github/leesiri1004/Colab/blob/main/1_2_NumpyTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 날짜 : 2021/02/01
# 이름 : 이슬이
# 내용 : 파이썬 Numpy 수치해석 라이브러리 실습하기

In [ ]:
import numpy as np

In [ ]:
# numpy 자료구조 - 벡터
v1 = np.array([1,2,3,4,5])
v1
v2 = np.arange(5)
v3 = np.arange(10)

print('v1 : ', v1)
print('v2 : ', v2)
print('v3 : ', v3)

v1 :  [1 2 3 4 5]
v2 :  [0 1 2 3 4]
v3 :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0 ~ 1 사이에 임의의 실수
rand1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
rand2 = np.random.rand(100)

# 0 ~ 9 사이에 임의의 정수
rand3 = np.random.rand(10)

In [ ]:
rand1

array([0.11532399, 0.92902791, 0.9359939 , 0.20521458, 0.6239885 ,
       0.36546142, 0.19712999, 0.86882367, 0.93406538, 0.45150751,
       0.44125452, 0.92811163, 0.49869877, 0.19130269, 0.52909619,
       0.27740456, 0.02485951, 0.51698595, 0.36046684, 0.6287584 ,
       0.07846992, 0.73996774, 0.94177309, 0.45226722, 0.95200261,
       0.57531163, 0.35840845, 0.50882313, 0.99604511, 0.23763025,
       0.41268373, 0.16605253, 0.48452867, 0.30368494, 0.94449549,
       0.21852487, 0.1358334 , 0.55885721, 0.31523872, 0.6648239 ,
       0.89382001, 0.55093096, 0.21948758, 0.89999661, 0.86780083,
       0.134746  , 0.72327704, 0.76784304, 0.77593346, 0.69854983,
       0.31397567, 0.16861328, 0.82745448, 0.29432682, 0.38998397,
       0.67825414, 0.023754  , 0.30109215, 0.52747256, 0.63633063,
       0.40894759, 0.19044895, 0.77846368, 0.12029121, 0.66880265,
       0.09434147, 0.71150644, 0.78723533, 0.25935541, 0.54408162,
       0.61845207, 0.65919818, 0.85888122, 0.19104283, 0.09894

In [ ]:
rand2

array([0.71611669, 0.63976411, 0.34796938, 0.73926104, 0.06199944,
       0.88591574, 0.5184641 , 0.28233032, 0.32343912, 0.18397542,
       0.46910866, 0.2794372 , 0.1885921 , 0.67690951, 0.01191412,
       0.53017222, 0.38564715, 0.40702124, 0.85024038, 0.1225321 ,
       0.96404379, 0.25309667, 0.84252297, 0.55422858, 0.64999661,
       0.75353437, 0.20276071, 0.21313724, 0.11152881, 0.08475634,
       0.79348119, 0.87290468, 0.78925914, 0.04707174, 0.36151116,
       0.42828604, 0.34331157, 0.32559499, 0.45301191, 0.06897993,
       0.66137351, 0.99825467, 0.14452667, 0.16265426, 0.73586007,
       0.35720094, 0.88491946, 0.68156217, 0.08196478, 0.12519259,
       0.10731387, 0.24008114, 0.61603637, 0.33567681, 0.90375898,
       0.5512346 , 0.29436907, 0.64117194, 0.70589339, 0.29553622,
       0.81925485, 0.83211935, 0.81181343, 0.62829462, 0.07848252,
       0.49902387, 0.3699256 , 0.87404085, 0.48212505, 0.74291511,
       0.28598961, 0.7564448 , 0.02325731, 0.61180619, 0.46694

In [ ]:
rand3

array([0.96373742, 0.44548567, 0.38641301, 0.85426416, 0.1214159 ,
       0.2039343 , 0.90525725, 0.1353296 , 0.03017998, 0.65225226])

In [ ]:
# 행렬
m1 = np.array([[1,2], [3,4]])
print(m1)

m2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 전치행렬
tm1 = m1.T
print(tm1)

tm2 = m2.transpose()
print(tm2)

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# 단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 행렬 인덱싱
mat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(mat)

print(mat[0,0])
print(mat[0,:])
print(mat[:,0])

print(mat[0:2, 0:2])
print(mat[:, 0:2])
print(mat[:, 2:4])
print(mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
